### ISSUE TITLE
Error running in Winx 10 cmd/powershell ; SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by SmeeFeux** [aleemrehmtulla/espanol-love#3]
```
.env
OPENAI_API_KEY=ab-1234567890abc...
```
---------------------------------------
```
C:\Users\me\AI\espanol-love>npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-darwin-x64@13.3.1 (node_modules\@next\swc-darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-darwin-x64@13.3.1: wanted {"os":"darwin","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-arm64-gnu@13.3.1 (node_modules\@next\swc-linux-arm64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-arm64-gnu@13.3.1: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-darwin-arm64@13.3.1 (node_modules\@next\swc-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-darwin-arm64@13.3.1: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-win32-ia32-msvc@13.3.1 (node_modules\@next\swc-win32-ia32-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-win32-ia32-msvc@13.3.1: wanted {"os":"win32","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-x64-musl@13.3.1 (node_modules\@next\swc-linux-x64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-x64-musl@13.3.1: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-arm64-musl@13.3.1 (node_modules\@next\swc-linux-arm64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-arm64-musl@13.3.1: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-win32-arm64-msvc@13.3.1 (node_modules\@next\swc-win32-arm64-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-win32-arm64-msvc@13.3.1: wanted {"os":"win32","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-x64-gnu@13.3.1 (node_modules\@next\swc-linux-x64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-x64-gnu@13.3.1: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})

audited 461 packages in 11.066s

109 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
---------------------------------------
```
C:\Users\me\AI\espanol-love>npm run dev

> espanol-love@0.1.0 dev C:\Users\me\AI\espanol-love
> next dev

C:\Users\me\AI\espanol-love\node_modules\next\dist\cli\next-dev.js:261
            showAll: args["--show-all"] ?? false,
                                         ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1070:16)
    at Module._compile (internal/modules/cjs/loader.js:1120:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.dev (C:\Users\me\AI\espanol-love\node_modules\next\dist\lib\commands.js:15:30)
    at Object.<anonymous> (C:\Users\me\AI\espanol-love\node_modules\next\dist\bin\next:144:28)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! espanol-love@0.1.0 dev: `next dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the espanol-love@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2023-05-02T16_47_29_014Z-debug.log
```
---------------------------------------
```
C:\Users\me\AppData\Roaming\npm-cache\_logs\2023-05-02T16_47_29_014Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle espanol-love@0.1.0~predev: espanol-love@0.1.0
6 info lifecycle espanol-love@0.1.0~dev: espanol-love@0.1.0
7 verbose lifecycle espanol-love@0.1.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle espanol-love@0.1.0~dev: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\me\AI\espanol-love\node_modules\.bin;C:\Program Files (x86)\VMware\VMware Player\bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;c:\Program Files (x86)\ZeroTier\One\;C:\Program Files\Git\cmd;C:\Users\me\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\me\AppData\Local\Programs\Python\Python310\;C:\Users\me\AppData\Local\Microsoft\WindowsApps;C:\Users\me\AppData\Roaming\npm
9 verbose lifecycle espanol-love@0.1.0~dev: CWD: C:\Users\me\AI\espanol-love
10 silly lifecycle espanol-love@0.1.0~dev: Args: [ '/d /s /c', 'next dev' ]
11 silly lifecycle espanol-love@0.1.0~dev: Returned: code: 1  signal: null
12 info lifecycle espanol-love@0.1.0~dev: Failed to exec dev script
13 verbose stack Error: espanol-love@0.1.0 dev: `next dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid espanol-love@0.1.0
15 verbose cwd C:\Users\me\AI\espanol-love
16 verbose Windows_NT 10.0.19045
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v12.16.2
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error espanol-love@0.1.0 dev: `next dev`
22 error Exit status 1
23 error Failed at the espanol-love@0.1.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by aleemrehmtulla** [comment]
> ```
> .env
> OPENAI_API_KEY=ab-1234567890abc...
> ```
> 
> ```
> C:\Users\me\AI\espanol-love>npm install
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-darwin-x64@13.3.1 (node_modules\@next\swc-darwin-x64):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-darwin-x64@13.3.1: wanted {"os":"darwin","arch":"x64"} (current: {"os":"win32","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-arm64-gnu@13.3.1 (node_modules\@next\swc-linux-arm64-gnu):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-arm64-gnu@13.3.1: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-darwin-arm64@13.3.1 (node_modules\@next\swc-darwin-arm64):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-darwin-arm64@13.3.1: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-win32-ia32-msvc@13.3.1 (node_modules\@next\swc-win32-ia32-msvc):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-win32-ia32-msvc@13.3.1: wanted {"os":"win32","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-x64-musl@13.3.1 (node_modules\@next\swc-linux-x64-musl):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-x64-musl@13.3.1: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-arm64-musl@13.3.1 (node_modules\@next\swc-linux-arm64-musl):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-arm64-musl@13.3.1: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-win32-arm64-msvc@13.3.1 (node_modules\@next\swc-win32-arm64-msvc):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-win32-arm64-msvc@13.3.1: wanted {"os":"win32","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-x64-gnu@13.3.1 (node_modules\@next\swc-linux-x64-gnu):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-x64-gnu@13.3.1: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
> 
> audited 461 packages in 11.066s
> 
> 109 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities
> ```
> 
> ```
> C:\Users\me\AI\espanol-love>npm run dev
> 
> > espanol-love@0.1.0 dev C:\Users\me\AI\espanol-love
> > next dev
> 
> C:\Users\me\AI\espanol-love\node_modules\next\dist\cli\next-dev.js:261
>             showAll: args["--show-all"] ?? false,
>                                          ^
> 
> SyntaxError: Unexpected token '?'
>     at wrapSafe (internal/modules/cjs/loader.js:1070:16)
>     at Module._compile (internal/modules/cjs/loader.js:1120:27)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
>     at Module.load (internal/modules/cjs/loader.js:1000:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
>     at Module.require (internal/modules/cjs/loader.js:1042:19)
>     at require (internal/modules/cjs/helpers.js:77:18)
>     at Object.dev (C:\Users\me\AI\espanol-love\node_modules\next\dist\lib\commands.js:15:30)
>     at Object.<anonymous> (C:\Users\me\AI\espanol-love\node_modules\next\dist\bin\next:144:28)
>     at Module._compile (internal/modules/cjs/loader.js:1156:30)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! espanol-love@0.1.0 dev: `next dev`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the espanol-love@0.1.0 dev script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2023-05-02T16_47_29_014Z-debug.log
> ```
> 
> ```
> C:\Users\me\AppData\Roaming\npm-cache\_logs\2023-05-02T16_47_29_014Z-debug.log
> 
> 0 info it worked if it ends with ok
> 1 verbose cli [
> 1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'dev'
> 1 verbose cli ]
> 2 info using npm@6.14.4
> 3 info using node@v12.16.2
> 4 verbose run-script [ 'predev', 'dev', 'postdev' ]
> 5 info lifecycle espanol-love@0.1.0~predev: espanol-love@0.1.0
> 6 info lifecycle espanol-love@0.1.0~dev: espanol-love@0.1.0
> 7 verbose lifecycle espanol-love@0.1.0~dev: unsafe-perm in lifecycle true
> 8 verbose lifecycle espanol-love@0.1.0~dev: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\me\AI\espanol-love\node_modules\.bin;C:\Program Files (x86)\VMware\VMware Player\bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;c:\Program Files (x86)\ZeroTier\One\;C:\Program Files\Git\cmd;C:\Users\me\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\me\AppData\Local\Programs\Python\Python310\;C:\Users\me\AppData\Local\Microsoft\WindowsApps;C:\Users\me\AppData\Roaming\npm
> 9 verbose lifecycle espanol-love@0.1.0~dev: CWD: C:\Users\me\AI\espanol-love
> 10 silly lifecycle espanol-love@0.1.0~dev: Args: [ '/d /s /c', 'next dev' ]
> 11 silly lifecycle espanol-love@0.1.0~dev: Returned: code: 1  signal: null
> 12 info lifecycle espanol-love@0.1.0~dev: Failed to exec dev script
> 13 verbose stack Error: espanol-love@0.1.0 dev: `next dev`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
> 13 verbose stack     at EventEmitter.emit (events.js:310:20)
> 13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:310:20)
> 13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
> 14 verbose pkgid espanol-love@0.1.0
> 15 verbose cwd C:\Users\me\AI\espanol-love
> 16 verbose Windows_NT 10.0.19045
> 17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
> 18 verbose node v12.16.2
> 19 verbose npm  v6.14.4
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error espanol-love@0.1.0 dev: `next dev`
> 22 error Exit status 1
> 23 error Failed at the espanol-love@0.1.0 dev script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]
> ```

two things to fix! 

first -- use node version 17.5.0

second -- change your env to follow `.envExample`

ps. node management is easier with `nvm`
