### ISSUE TITLE
gets stuck here

### ISSUE THREAD

**Issue by ravindranantony** [aleemrehmtulla/espanol-love#4]
![image](https://user-images.githubusercontent.com/83961191/235866739-fefde597-9655-402f-8953-af501fad9771.png)

**Comment by aleemrehmtulla** [comment]
> ![image](https://user-images.githubusercontent.com/83961191/235866739-fefde597-9655-402f-8953-af501fad9771.png)

i'm gonna need more context than that to help ya 😝 

was this local? was it on the demo site?

do you have env file? what were the logs?

**Comment by ravindranantony** [comment]
i built it and put it on vercel and it does not work there. https://epsonallove.vercel.app/

**Comment by aleemrehmtulla** [comment]
> i built it and put it on vercel and it does not work there. https://epsonallove.vercel.app/

what about the other questions homie!

my best guess is you haven't added your environment variables to vercel, or it's timing out and ya need to put it on a pro plan. really can't help much with out more information :/

**Comment by aleemrehmtulla** [comment]
> > i built it and put it on vercel and it does not work there. https://epsonallove.vercel.app/
> 
> what about the other questions homie!
> 
> my best guess is you haven't added your environment variables to vercel, or it's timing out and ya need to put it on a pro plan. really can't help much with out more information :/

going to close this issue now! lmk if you need anything else
